### ISSUE TITLE
Assignment - 5: Palindrome Checker

### ISSUE THREAD

**Issue by 55bit23** [vtcbca/basic-programming-65bit23#4]
Can a number like 12321 be a palindrome?

**Comment by 55bit23** [comment]
Yes, numeric palindromes exist when they read the same backward.

**Comment by 65bit23** [comment]
Yes, numeric palindromes exist when they read the same backward.

**Comment by 55bit23** [comment]
What happens if the input has punctuation or special characters?

**Comment by 65bit23** [comment]
The program may consider them unless you remove them using functions like re.sub().

**Comment by 55bit23** [comment]
How can you test multiple strings for palindromes in one go?

**Comment by 65bit23** [comment]
Use a loop to check each string in a list:

```
for word in words:
    if word == word[::-1]:
        print(f"{word} is a palindrome.")
```

**Comment by 55bit23** [comment]
Is there a limit to the size of a palindrome string in Python?

**Comment by 55bit23** [comment]
No, Python can handle very large strings, limited only by memory.

**Comment by 65bit23** [comment]
No, Python can handle very large strings, limited only by memory.

**Comment by 55bit23** [comment]
got it thanks !
